use_frameworks!

project 'native-navigation.xcodeproj'

target 'native-navigation' do
  pod 'yoga', :path => '../../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'native-navigation', :path => '../../'
  pod 'React', :path => '../../node_modules/react-native', :subspecs => [
    'BatchedBridge',
    'Core',
    'DevSupport',
    'RCTAnimation',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
  ]
end
